finish description of the chosen system
dyc3/sys-581-group-project pull request #112
Opened 2024-05-11 19:14 UTC by dyc3

2024-05-11 19:14 UTC, dyc3 commented
* **#112** <a href="https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/112?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dyc3 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-12 19:28 UTC, smcdonou02 requested changes
Change “is comprises” to “is comprised of”

2024-05-12 19:35 UTC, smcdonou02 approved these changes

2024-05-12 19:49 UTC, dyc3 commented
### Merge activity

* **May 12, 3:49 PM EDT**: @dyc3 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dyc3/sys-581-group-project/112).

2024-05-12 19:49 UTC, merged